name: route_gen
description: Route generator
version: 0.0.1

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  source_gen: ^1.0.2
  build: ^2.0.2
  basic_utils: ^3.1.0